### PR TITLE
Fix build error

### PR DESCRIPTION
**Pull request by PangMo5**
- Fixed some errors using templates. 
- Add some parameters to openapi-generator

## Known issues
- It does not work properly with https://api.jellyfin.org/openapi/jellyfin-openapi-stable.json. 
So worked on https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/HNpQuMfIXMGlbdZVKjRucsFO
- Due to the nature of the Swift language, recursion problems occur in properties CurrentProgram of BaseItemDTO and AlbumArtist of RemoteSearchResult. 
Currently, the deleted part is saved as api.json and used.
In the future, that part may have to be processed with AnyCodable or we will have to find another generator. 
- All properties of models are created as optional.

### CODE REVIEW

**Comment by acvigue** [comment]
is 10.7.6 compatible with latest

**Comment by PangMo5** [comment]
Add type-mappings UUID -> String 
Because Jellyfin's UUID is not mapping with Codable (has't hyphen)

And I simply tested the SearchAPI.callGet API in Swiftfin and confirmed that it works.
https://github.com/pangmo5/jellyfin-sdk-swift/blob/main/docs/SearchAPI.md#callget

**Comment by acvigue** [comment]
you’re amazing. i’ll look into this after dinner

**Comment by acvigue** [comment]
could you send some example code? it builds but I don't know how to set the server url and auth token

**Comment by PangMo5** [comment]
> could you send some example code? it builds but I don't know how to set the server url and auth token

First, `import JellyfinAPI` where use at APIs or Models.
And set up basePath and customHeaders like this
```
JellyfinAPI.basePath = globalData.server?.baseURI ?? ""
JellyfinAPI.customHeaders = ["X-Emby-Authorization": header]
```
For now, I set it below the place where the header is created in startUp func in ContentView.

In API, Created request for use with Combine in ViewModel.
You can use this like below.
```
// ex callGet of SearchAPI
SearchAPI.callGet(searchTerm: query, userId: globalData.user?.user_id)
	.replaceError(with: .init(searchHints: [], totalRecordCount: 0)) // for assign. or keep the stream from being interrupted. 
	.compactMap(\.searchHints)
	.assign(to: \.newItems, on: self) // or sink value
	.store(in: &cancellables)
```
Reference: https://developer.apple.com/documentation/combine/receiving-and-handling-events-with-combine

**Comment by acvigue** [comment]
hmm am getting this error: 
```
CredStore - performQuery - Error copying matching creds.  Error=-50
```

**Comment by acvigue** [comment]
Screen Shot 2021-06-05 at 9 37 50 AM

**Comment by PangMo5** [comment]
Other APIs not working too?

**Comment by acvigue** [comment]
Hmm. No. Can you send me the full file with example code?

**Comment by PangMo5** [comment]
check this branch 
https://github.com/PangMo5/Swiftfin/tree/PangMo5/jellyfinAPI

**Pull request merged**
